title: Mohammad Yaghmouri
logo: headshot_circle.png
description: mohammadyaghmoury@gmail.com  
This is Mohammad yaghmouri , a passionate data analyst who delves deep into
big data in the field of biology and business to make data-driven decisions and strategies
Here you can see my coding samples in SQL , R , and Python

show_downloads: False
theme: jekyll-theme-minimal
