title: Mohammad Yaghmouri
logo: headshot_circle.png
description: mohammadyaghmoury@gmail.com  A passionate data analyst who delves deep into big data in the field of biology and business to make data-driven decisions and strategies
show_downloads: False
theme: jekyll-theme-minimal
